name: 'Add binary to release'
description: 'Upload a binary to an already-existing GitHub Release.'
inputs:
  path:
    description: 'File to upload. Does not support wildcards.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
